setwd("/Users/spandana/Desktop")
powerdata <- read.csv("/Users/spandana/Desktop/household_power_consumption.txt",header=T,sep=";",na.strings="?")
twodays <- subset(powerdata,Date %in% c("1/2/2007", "2/2/2007"))
twodays$Date <- as.Date(twodays$Date,format="%d/%m/%Y")
twodaydatetime <- paste(as.Date(twodays$Date),twodays$Time)
twodays$Datetime <- as.POSIXct(twodaydatetime)
with(twodays,{plot(Global_active_power~Datetime,type="l",ylab="Global Active Power(kilowatts)",xlab="")})

dev.copy(png,file="/Users/spandana/Desktop/plot2.png",height=480, width=480)
dev.off()