setwd("/Users/spandana/Desktop")
powerdata <- read.csv("/Users/spandana/Desktop/household_power_consumption.txt",header=T,sep=";",na.strings="?")
twodays <- subset(powerdata,Date %in% c("1/2/2007", "2/2/2007"))
twodays$Date <- as.Date(twodays$Date,format="%d/%m/%Y")
twodaydatetime <- paste(as.Date(twodays$Date),twodays$Time)
twodays$Datetime <- as.POSIXct(twodaydatetime)
with(twodays,{plot(Sub_metering_1~Datetime,type="l",ylab="Energy sub metering",xlab="")
  lines(Sub_metering_2~Datetime,col="Red")
  lines(Sub_metering_3~Datetime,col="Blue")
  })
legend("topright",col=c("black","red","blue"),lty=1,lwd=2,
       legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))

dev.copy(png,file="/Users/spandana/Desktop/plot3.png",height=480, width=480)
dev.off()
